### ISSUE TITLE
Repair HTML a tag issues

### ISSUE THREAD

**Issue by flucium** [Flasushi/Flasushi.github.io#1]
**Fix:**
`<a href="flash.osushi@gmail.com"> Mail </a>`.

**Location:**
https://github.com/Flasushi/Flasushi.github.io/blob/22b70a7ecdc42b2099221a4e7066cc6d851cb3c7/index.html#L51C1-L52C1

**Comment:**
if you mean mailto, then rewrite `<a href="flash.osushi@gmail.com">` as `<a href="mailto:flash.osushi@gmail.com">`.

**Comment by Flasushi** [comment]
### Thank you! flucium!
slipped my mind for 5 years👀
